title: Abdul Mateen Chronicles
description: Personal portfolio and university journal of Abdul Mateen, a Computer Engineering learner at UET Faisalabad Campus.
url: "https://ab-mateensethi.github.io"
baseurl: ""
timezone: Asia/Karachi
markdown: kramdown
permalink: /blog/:title/
exclude:
  - backup
