title: Ab Mateen Sethi
description: Personal website and university journal of Ab Mateen Sethi, a Computer Engineering student from Dina studying in Faisalabad.
url: "https://ab-mateensethi.github.io"
baseurl: ""
timezone: Asia/Karachi
markdown: kramdown
permalink: /blog/:title/
exclude:
  - backup
